"""remove test

Revision ID: 012d467ef9ef
Revises: 59dac1e4f888
Create Date: 2024-12-08 17:47:13.093472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012d467ef9ef'
down_revision: Union[str, None] = '59dac1e4f888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
