"""test

Revision ID: 59dac1e4f888
Revises: ff35f9d174d0
Create Date: 2024-12-08 17:46:45.412230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59dac1e4f888'
down_revision: Union[str, None] = 'ff35f9d174d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'test')
    # ### end Alembic commands ###
