"""location column added to drop model

Revision ID: 5f8f67e5de7c
Revises: e94bd35a9c76
Create Date: 2024-12-15 20:46:26.314891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8f67e5de7c'
down_revision: Union[str, None] = 'e94bd35a9c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('drops', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'longitude')
    op.drop_column('drops', 'latitude')
    # ### end Alembic commands ###
