"""removed certain aspects of user

Revision ID: 64883e601f95
Revises: cf35b54f2f40
Create Date: 2024-09-04 11:11:46.857517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64883e601f95'
down_revision: Union[str, None] = 'cf35b54f2f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'jobs_applied')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jobs_applied', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('middle_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('github_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
