"""added user_id field to Drop and drops field to User

Revision ID: ff35f9d174d0
Revises: 62cd0b7d706f
Create Date: 2024-09-14 18:53:21.884708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff35f9d174d0'
down_revision: Union[str, None] = '62cd0b7d706f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'drops', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('drops', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'drops')
    op.drop_constraint(None, 'drops', type_='foreignkey')
    op.drop_column('drops', 'user_id')
    # ### end Alembic commands ###
